Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Vui.Models
{
    public class Post
    {
        [Key]
        public long Id {get;set;}
        [Display(Name="Posted Date")]
        public DateTime PostedDate { get; set; }
        [Display(Name = "Title")]
        [Required]
        [StringLength(50,ErrorMessage="Title has to be less than 50 characters")]    
        [Column(TypeName="varchar")]
        public string Title { get; set; }
        [Required]
        [StringLength(200)]        
        [Column(TypeName="varchar")]
        [Display(Name="Selected file")]
        public string url { get; set; }
        [Display(Name = "Likes")]
        public int TotalLikes {get;set;}        
        [Display(Name = "Comments")]
        public int TotalComments {get;set;}


        public virtual ICollection<LikeActivity> LikeActivities { get; set; }
        public virtual ICollection<CommentActivity> CommentActivities { get; set; }        
        public virtual ApplicationUser User { get; set; }
        [Required]
        public string ApplicationUserId { get; set; }
    }
}

Models/PostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Vui.Models
{
    public class UploadFileModel
    {
        [Display(Name = "Title")]
        [Required]
        [StringLength(50, ErrorMessage = "Title has to be less than 50 characters")]
        [Column(TypeName = "varchar")]
        public string title { get; set; }
                
        //public File url { get; set; }
    }
    
}

Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vui.Models;

namespace Vui.Controllers
{
    [Authorize]
    public class ActivityController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Activity/Like
        public ActionResult Like()
        {
            return View();
        }
        //[HttpPost]
        //public ActionResult Like(LikeActivity act)
        //{
        //    if (ModelState.IsValid)
        //    {                
        //        //db.LikeActivities.Add(act);
        //        db.SaveChanges();
        //        return RedirectToAction("Index", "Home");
        //    }
        //    return View();
        //}
    }
}

Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vui.Models;

namespace Vui.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LikeComment()
        {
            string userId = Request.Params["userId"];
            string sortOrder = Request.Params["sortOrder"];
            long commentId = long.Parse(Request.Params["commentId"]);
            long postId = long.Parse(Request.Params["postId"]);
            CommentActivity comment = db.CommentActivities.Where(c => c.CommentId == commentId).First();
            //comment.User = db.Users.Where(us => us.Id == comment.ApplicationUserId).First();           
            if (comment.LikeActivities.Where(c => c.CommentId == commentId).Count() == 0)
            {
                LikeActivity act = new LikeActivity();
                act = new LikeActivity();
                //act.Id = db.LikeActivities.Count() + 1;
                act.ApplicationUserId = userId;
                act.PostId = postId;
                act.CommentId = commentId;
                act.Like = true;
                //db.LikeActivities.Add(act);
                comment.LikeActivities.Add(act);
                comment.TotalLikes++;
            }
            else
            {
                LikeActivity act = comment.LikeActivities.Where(c => c.CommentId ==
                    commentId).First();
                if (!act.Like)
                {
                    comment.TotalLikes++;
                }                
                act.CommentId = commentId;
                act.Like = true;
              //  ViewBag.LikeComment = "UnLike";
            }
            try
            {
                db.SaveChanges();
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw;
            }
            return RedirectToAction("Index","Home");
        }

        public ActionResult UnLikeComment()
        {
            //string userId = Request.Params["userId"];
            string sortOrder = Request.Params["sortOrder"];
            long commentId = long.Parse(Request.Params["commentId"]);
            long postId = long.Parse(Request.Params["postId"]);
            CommentActivity comment = db.CommentActivities.Where(c => c.CommentId == commentId).First();
            LikeActivity likeAct = comment.LikeActivities.Where(c => c.CommentId == commentId).First();
            likeAct.Like = false;
            //ViewBag.LikeComment = "Like";
            comment.TotalLikes--;            
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

       

        // GET: Comment/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Comment/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Comment/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Comment/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Comment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Comment/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Comment/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vui.Models;
using Microsoft.AspNet.Identity;
using PagedList;
namespace Vui.Controllers
{
    public class PostController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Post
        [Authorize]
        public ActionResult Index(string sortOrder,int? page)
        {           
            //var posts = from s in db.Posts select s;            
            string userId = User.Identity.GetUserId();
            var posts = db.Posts.Where(p => p.ApplicationUserId == userId);
            if (posts != null && posts.Count() != 0)
            {
                switch (sortOrder)
                {
                    case "title_desc":
                        posts = posts.OrderByDescending(s => s.Title);
                        ViewBag.SortByTitle = "";
                        ViewBag.SortByDate = "date";
                        break;
                    case "date":
                        posts = posts.OrderBy(s => s.PostedDate);
                        ViewBag.SortByDate = "date_desc";
                        break;
                    case "date_desc":
                        posts = posts.OrderByDescending(s => s.PostedDate);
                        ViewBag.SortByDate = "date";
                        break;
                    case "like":
                        posts = posts.OrderBy(s => s.TotalLikes);
                        ViewBag.SortByDate = "like";
                        break;
                    case "comment":
                        posts = posts.OrderBy(s => s.TotalComments);
                        ViewBag.SortByDate = "comment";
                        break;
                    default:
                        posts = posts.OrderBy(s => s.Title);
                        ViewBag.SortByTitle = "title_desc";
                        ViewBag.SortByDate = "date";
                        break;
                }
                ViewBag.CurrentSort = sortOrder;
                int pageSize = 6;
                int pageNumber = (page ?? 1);
                ViewBag.CurrentPage = pageNumber;                
                return View(posts.ToPagedList(pageNumber, pageSize));
            }
            return View("Index", null);
        }
        

        // GET: Post/Details/5
        public ActionResult Details()
        {
            //var post = new Post { Id = 1, postedDate = DateTime.Now, title = "so fun", url = "/Content/images/pic1.jpg" };
            long postId = long.Parse(Request.Params.Get("postId"));
            Post post = db.Posts.Where(c => c.Id == postId).First();
            return View("Details",post);
        }

        // GET: Post/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Post/Create
        [HttpPost]
        [Authorize]
        public ActionResult Create(UploadFileModel model, HttpPostedFileBase FileUpload)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid && FileUpload != null)
                {
                    Post post = new Post();
                    var fileName = Path.GetFileName(FileUpload.FileName);
                    var serverPath = Path.Combine(Server.MapPath("~/Content/images/"), fileName);
                    FileUpload.SaveAs(serverPath);
                    post.url = "/Content/images/"+fileName;
                    post.Title = model.title;
                    int count = db.Posts.Count();
                    post.Id = count + 1;
                    post.PostedDate = DateTime.Now;
                    post.ApplicationUserId = User.Identity.GetUserId();
                    db.Posts.Add(post);
                    db.SaveChanges();                
                    return RedirectToAction("Details", "Post", new {postId = post.Id});
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        [Authorize]
        public ActionResult LikeOrComment(string returnUrl)
        {
            //long postId = long.Parse(Request.Form["postId"]);
            //string sortOrder = Request.Form["sortOrder"];
            //string pageNo = Request.Form["pageNo"];
            //Post post = db.Posts.Where(p => p.Id == postId).First();
            //string userId = User.Identity.GetUserId();
            //string like_com = Request.Form["like_com"];
            long postId = long.Parse(Request.Params["postId"]);
            string sortOrder = Request.Params["sortOrder"];
            string pageNo = Request.Params["pageNo"];
            Post post = db.Posts.Where(p => p.Id == postId).First();
            string userId = User.Identity.GetUserId();
            string like_com = Request.Params["like_com"];

            if (like_com == "Like")
            {
                if (db.LikeActivities.Where(activity => activity.PostId == postId &&
                    activity.ApplicationUserId == userId).Count() == 0)
                {
                    LikeActivity act = new LikeActivity();
                    act = new LikeActivity();
                    //act.Id = db.LikeActivities.Count() + 1;
                    act.ApplicationUserId = userId;
                    act.PostId = postId;
                    act.Like = true;
                    db.LikeActivities.Add(act);
                    post.TotalLikes++;
                }
                else
                {
                    LikeActivity likeAct = db.LikeActivities.Where(activity => activity.PostId ==
                        postId && activity.ApplicationUserId == userId).First();
                    if (!likeAct.Like)
                    {
                        post.TotalLikes++;
                    }
                    likeAct.Like = true;
                    ViewBag.Like = "UnLike";
                }
                
                db.SaveChanges();

            }
            else if (like_com == "UnLike")
            {
                LikeActivity likeAct = db.LikeActivities.Where(activity => activity.PostId ==
                      postId && activity.ApplicationUserId == userId).First();
                likeAct.Like = false;
                ViewBag.Like = "Like";
                post.TotalLikes--;
                db.SaveChanges();
            }
            else if (like_com == "Comment")
            {
                string comment = Request.Params["UserComment"];
                if (!string.IsNullOrWhiteSpace(comment))
                {
                    CommentActivity act = new CommentActivity();
                    act.ApplicationUserId = userId;
                    act.PostId = postId;
                    act.Comment = comment;
                    act.User = db.Users.Where(us => us.Id == User.Identity.GetUserId()).First();
                    db.CommentActivities.Add(act);                                            
                    post.TotalComments++;                    
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Index", "Post", new { sortOrder= "date", page=1});
        }

        public ActionResult ViewComment()
        {

            return View();
        }
        // GET: Post/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Post/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Post/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Post/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Post/CommentView.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

Views/Post/Create.cshtml
@model Vui.Models.UploadFileModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Post", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })      
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2" for="title"></label>
            <input class="btn" type="file" name="FileUpload" />
        </div>
        <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Post" class="btn btn-default" />
                </div>
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Post/Details.cshtml
@model Vui.Models.Post

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

@*<div>
    <h4>Post</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.postedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.postedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url)
        </dd>

    </dl>
</div>*@
<div class="row">
    <div class="col-md-4 margin-top-20">
        <img class="img-responsive" src="@Model.url" />
        @ViewBag.TotalLikes <a href="@Url.Action("Like", "Activity", new { postId = ViewBag.PostId})"
                               class="btn btn-primary margin-top-20">Like</a>
    </div>

</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Post/Index.cshtml
@model PagedList.IPagedList<Vui.Models.Post>
@using PagedList.Mvc;
@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "Index";
}
<div class="dropdown">
    <button class="btn btn-primary dropdown-toggle margin-top-10" type="button" data-toggle="dropdown">
        Sort By
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        <li><a href="@Url.Action("Index", "Post", new { sortOrder = ViewBag.SortByTitle })">Title</a></li>
        <li><a href="@Url.Action("Index", "Post", new { sortOrder = ViewBag.SortByDate })">Date</a></li>
        <li><a href="@Url.Action("Index", "Post", new { sortOrder = ViewBag.SortByLike})">Like</a></li>
        <li><a href="@Url.Action("Index", "Post", new { sortOrder = ViewBag.SortByComment })">Comment</a></li>
    </ul>
</div>
@if (Model != null)
{
    int i = 0;
    <div class="row">
        @foreach (var item in Model)
        {
            if (item != null)
            {
                Html.RenderPartial("_PictureModal", item, new ViewDataDictionary { { "controller", "Post" },{"counter",i} });
                i++;
            }
        }

    </div>

    int page = Model.PageCount ;
    if(page <Model.PageCount){
        page = 0;
    }else{
        page = Model.PageNumber;
    }
    <text>Page</text> @page <text>of</text> @Model.PageCount

    Html.PagedListPager(Model, p => Url.Action("Index", "Post",
        new { p, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }));
}
<br />